import = [
    "~/.config/alacritty/themes/themes/catppuccin_match.toml"
]

[env]
TERM = "xterm-256color"

[window.padding]
x = 10
y = 10

[window]
blur = true
decorations = "Buttonless"
opacity = 0.8
option_as_alt = "Both"


[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
